#!/bin/bash
PYFILE="$PYFILE"
PYCFILE="${PYFILE%.py}.pyc"

if [ -z "$PYFILE" ]; then
    echo "PYFILE environment variable is not set."
    exit 1
fi

python3 -m py_compile "$PYFILE" && mv "__pycache__/$PYCFILE" .

if [ -f "$PYCFILE" ]; then
    echo "Compilation successful."
else
    echo "Compilation failed."
fi
